### ISSUE TITLE
Not working with firmware [20201118] and split device

### ISSUE THREAD

**Issue by IngoMWestner** [markus-i/AHK-EDToggle#1]
With the newer firmware [20201118] which allows me to split the joystick/throttle in 2 USB devices, the script isn't working anymore. I did not find a workaround, so far. Any ideas?

**Comment by markus-i** [comment]
Since the only thing that the script is taking from the stick are the stick and button numbers (1joy1 and 2joy1), I'd guess that the firmware changes either the joystick number and/or the button number. Best I can suggest: open the windows joystick tool (control panel -> Hardware and Sound -> Devices and Printers -> right-click on the joystick, the go for properties), then toggle the flip switch and see which button number is flipping for Windows:
![grafik](https://user-images.githubusercontent.com/44025590/205957421-36b4ee71-a32a-4080-84ed-6168b38e95fe.png)

If that's still button 1 (or you can asigne the flipper to button 1 in the firmware/configuration tool), then you "only" need to find out which joystick number now is assigned in Windows to that stick. Since there aren't too many, it shouldn't be too difficult. The trace outputs via msgBox are still in the script, just uncomment them if you don't want to fire up ED any time you want to check changes.

Alternatively - did you check that the recent ED update didn't wipe your bindings, i.e. are the scripts trigger outputs (ctrl-H and ctrl-M) still bound to hardpoints and cockpit mode?

**Comment by IngoMWestner** [comment]
Apologies for necroposting. You were right: the joystick IDs were shuffled when I made a firmware update and installed another mouse in parallel. Thank you for your help!
